feat(workflows): integrate `squash-merge` and `rebase-merge` action (#2772)

diff --git a/.github/workflows/gh_action_merge.yml b/.github/workflows/gh_action_merge.yml
--- a/.github/workflows/gh_action_merge.yml
+++ b/.github/workflows/gh_action_merge.yml
@@ -10,31 +10,9 @@ on:
     types:
       - labeled
 
-env:
-  OUTPUT_FUNCTION: |
-    function output {
-      if [ $1 -ne 0 ]; then
-          if [[ -z "$2" ]]; then
-            echo "failed_result=(empty response)" >> $GITHUB_OUTPUT
-          else
-            echo "failed_result<<EOF" >> $GITHUB_OUTPUT
-            echo "$2" >> $GITHUB_OUTPUT
-            echo "EOF" >> $GITHUB_OUTPUT
-          fi
-          exit 0
-      fi
-    }
-
 jobs:
-  call_classify_commits:
-    if: github.repository == 'Tencent/Hippy' && (github.event.label.name == 'action(squash-merge)' || github.event.label.name == 'action(rebase-merge)')
-    uses: ./.github/workflows/reuse_classify_commits.yml
-    with:
-      pull_request_number: ${{ github.event.pull_request.number }}
-
   squash_merge_action:
-    needs: call_classify_commits
-    if: github.event.label.name == 'action(squash-merge)'
+    if: github.event.label.name == 'action(squash-merge)' && github.repository == 'Tencent/Hippy'
     runs-on: ubuntu-latest
     steps:
     - name: Token
@@ -43,26 +21,26 @@ jobs:
       with:
         private-key: ${{ secrets.ACTION_PRIVATE_KEY }}
         app-id: ${{ secrets.ACTION_APP_ID }}
-    - name: Reset
+    - name: Check
       if: "contains(github.event.pull_request.labels.*.name, 'action(squash-merge): failed')"
       uses: actions-ecosystem/action-remove-labels@v1.3.0
       with:
         github_token: ${{ steps.get-token.outputs.token }}
         labels: "action(squash-merge): failed"
     - name: Checkout
-      if: needs.call_classify_commits.outputs.normal_commits_count > 1
+      if: github.event.pull_request.commits > 1
       uses: actions/checkout@v3
       with:
         fetch-depth: 0
     - name: Setup
-      if: needs.call_classify_commits.outputs.normal_commits_count > 1
+      if: github.event.pull_request.commits > 1
       uses: actions/setup-node@v3
       with:
         node-version: 16.x
         cache: 'npm'
         cache-dependency-path: package-lock.json
     - name: Install
-      if: needs.call_classify_commits.outputs.normal_commits_count > 1
+      if: github.event.pull_request.commits > 1
       run: |
         npm install commitlint-plugin-function-rules@1.6.0 @commitlint/cli@16.2.1 @commitlint/config-conventional@16.2.1 @commitlint/lint@16.2.1 @commitlint/prompt-cli@16.2.1
     - name: Commitlint
@@ -71,23 +49,37 @@ jobs:
         PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
       shell: bash {0}
       run: |
-        ${{ env.OUTPUT_FUNCTION }}
-        if [ ${{ needs.call_classify_commits.outputs.normal_commits_count }} -gt 1 ]; then
+        if [ ${{ github.event.pull_request.commits }} -gt 1 ]; then
           result=`echo $PULL_REQUEST_TITLE | npx commitlint -c false 2>&1`
-          output $? "$result"
+          if [ $? -ne 0 ]; then
+            if [[ -z $result ]]; then
+              echo "failed_result=(empty response)" >> $GITHUB_OUTPUT
+            else
+              echo "failed_result<<EOF" >> $GITHUB_OUTPUT
+              echo "$result" >> $GITHUB_OUTPUT
+              echo "EOF" >> $GITHUB_OUTPUT
+            fi
+          fi
         fi
+        exit 0
     - name: Squash
       id: squash
-      if: ${{ !steps.commitlint.outputs.failed_result && github.event.pull_request.user.login != github.event.sender.login }}
+      if: ${{ !steps.commitlint.outputs.failed_result }}
       env:
         GH_TOKEN: ${{ steps.get-token.outputs.token }}
       shell: bash {0}
       run: |
-        ${{ env.OUTPUT_FUNCTION }}
-        result=`gh pr merge ${{ github.event.pull_request.number }} --disable-auto --repo $GITHUB_REPOSITORY 2>&1`
-        output $? "$result"
         result=`gh pr merge ${{ github.event.pull_request.number }} --squash --auto --repo $GITHUB_REPOSITORY 2>&1`
-        output $? "$result"
+        if [ $? -ne 0 ]; then
+            if [[ -z $result ]]; then
+              echo "failed_result=(empty response)" >> $GITHUB_OUTPUT
+            else
+              echo "failed_result<<EOF" >> $GITHUB_OUTPUT
+              echo "$result" >> $GITHUB_OUTPUT
+              echo "EOF" >> $GITHUB_OUTPUT
+            fi
+        fi
+        exit 0
     - name: Comment
       uses: actions/github-script@v6.3.3
       env:
@@ -105,22 +97,19 @@ jobs:
 
           </details>
 
-          ${{ github.event.sender.type == 'User' && format('@{0}', github.event.sender.login) || '#help' }}
+          @${{ github.event.sender.login }}
       with:
         github-token: ${{ steps.get-token.outputs.token }}
         script: |
-          const { pull_request, sender } = context.payload;
+          const { pull_request } = context.payload;
           const { issues } = github.rest;
           const util = require('util');
-          const os = require('os');
 
           let body;
           if (process.env.CHECK_RESULT) {
             body = util.format(process.env.FAILED_MESSAGE, 'pull request title does not meet the [Convention Commit](https://conventionalcommits.org/) guideline', process.env.CHECK_RESULT);
           } else if (process.env.SQUASH_RESULT) {
             body = util.format(process.env.FAILED_MESSAGE, 'auto squash and merge failed', process.env.SQUASH_RESULT);
-          } else if (pull_request.user.login === sender.login) {
-            body = util.format(process.env.FAILED_MESSAGE, 'cannot squash and merge your own pull request', `(empty response)`);
           }
 
           const p = [];
@@ -145,43 +134,24 @@ jobs:
           }
           await Promise.all(p);
 
-  rebase_merge_action_preparation:
-    needs: call_classify_commits
-    if: github.event.label.name == 'action(rebase-merge)'
+  rebase_merge_action:
+    if: github.event.label.name == 'action(rebase-merge)' && github.repository == 'Tencent/Hippy'
     runs-on: ubuntu-latest
-    outputs:
-      permission: ${{ steps.get-permission.outputs.permission }}
     steps:
-    - name: Permission
-      id: get-permission
-      uses: actions/github-script@v6.3.3
-      with:
-        script: |
-          const { repos } = github.rest;
-          const fs = require('fs');
-          const os = require('os');
-
-          const { data: { permission } } = await repos.getCollaboratorPermissionLevel({
-            ...context.repo,
-            username: "${{ github.event.sender.login }}"
-          });
-          fs.appendFileSync(process.env.GITHUB_OUTPUT, `permission=${permission}${os.EOL}`, { encoding: 'utf8' });
     - name: Token
       uses: navikt/github-app-token-generator@v1
-      if: steps.get-permission.outputs.permission != 'admin' && needs.call_classify_commits.outputs.normal_commits_count > 1
       id: get-token
       with:
         private-key: ${{ secrets.ACTION_PRIVATE_KEY }}
         app-id: ${{ secrets.ACTION_APP_ID }}
     - name: Comment
-      if: steps.get-token.outputs.token
       env:
         COMMENT_MESSAGE: |
           :lock: `rebase-merge` action execution needs privilege escalation.
 
           Please wait for admin team member approval ...
 
-          ${{ github.event.sender.type == 'User' && format('@{0}', github.event.sender.login) || '' }}
+          @${{ github.event.sender.login }}
         WECHAT_WORK_MESSAGE: |
           [${{ github.event.sender.login }}](https://github.com/${{ github.event.sender.login }}) requested privilege escalation action on [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) pull request.
           > ${{ github.event.pull_request.title }}
@@ -223,10 +193,10 @@ jobs:
                     text_color: "2c974b"
                   }, {
                     name: "reject_btn",
-                    text: "Mark as Rejected",
+                    text: "Mark as Reject",
                     type: "button",
-                    value: "Mark as Rejected",
-                    replace_text: "Already Rejected",
+                    value: "Mark as Reject",
+                    replace_text: "Already Reject",
                     border_color: "cf222e",
                     text_color: "cf222e"
                   }, {
@@ -245,10 +215,10 @@ jobs:
 
           await Promise.all(p);
 
-  rebase_merge_action:
-    needs: [ rebase_merge_action_preparation, call_classify_commits ]
+  rebase_merge_action_privileged:
+    needs: [ rebase_merge_action ]
     runs-on: ubuntu-latest
-    environment: ${{ (needs.rebase_merge_action_preparation.outputs.permission != 'admin' && needs.call_classify_commits.outputs.normal_commits_count > 1) && 'github-actions-privileged' || '' }}
+    environment: github-actions-privileged
     steps:
     - name: Token
       uses: navikt/github-app-token-generator@v1
@@ -268,11 +238,17 @@ jobs:
         GH_TOKEN: ${{ steps.get-token.outputs.token }}
       shell: bash {0}
       run: |
-        ${{ env.OUTPUT_FUNCTION }}
-        result=`gh pr merge ${{ github.event.pull_request.number }} --disable-auto --repo $GITHUB_REPOSITORY 2>&1`
-        output $? "$result"
         result=`gh pr merge ${{ github.event.pull_request.number }} --rebase --auto --repo $GITHUB_REPOSITORY 2>&1`
-        output $? "$result"
+        if [ $? -ne 0 ]; then
+            if [[ -z $result ]]; then
+              echo "failed_result=(empty response)" >> $GITHUB_OUTPUT
+            else
+              echo "failed_result<<EOF" >> $GITHUB_OUTPUT
+              echo "$result" >> $GITHUB_OUTPUT
+              echo "EOF" >> $GITHUB_OUTPUT
+            fi
+        fi
+        exit 0
     - name: Comment
       uses: actions/github-script@v6.3.3
       env:
@@ -289,7 +265,7 @@ jobs:
 
           </details>
 
-          ${{ github.event.sender.type == 'User' && format('@{0}', github.event.sender.login) || '#help' }}
+          @${{ github.event.sender.login }}
       with:
         github-token: ${{ steps.get-token.outputs.token }}
         script: |
@@ -319,8 +295,8 @@ jobs:
           }
           await Promise.all(p);
 
-  rebase_merge_action_rejected:
-    needs: [ rebase_merge_action ]
+  rebase_merge_action_reject:
+    needs: [ rebase_merge_action_privileged ]
     if: failure()
     runs-on: ubuntu-latest
     steps:
